# This is a basic workflow to help you get started with Actions

name: Test Create Issue

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  issues: write 

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_NO_LOG_TIMESTAMPS: true
    UPLOAD_FOLDER: tmp
    SIZE_FOLDER: size_reports
    BIN_FOLDER: bin_files
    
jobs:
    test-create_issue:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          # Either the following steps can create an issue

          # - name: Create an issue
          #   run: python3 scripts/workflow/create_issue.py "${{ github.token }}" "${{github.repository_owner}}" "${{github.repository}}"

          # - name: Create an issue
          #   uses: dacbd/create-issue-action@main
          #   with:
          #     token: ${{ github.token }}
          #     title: Simple test issue
          #     body: my new issue
          #     assignees: eling22
